# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArticles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=35)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('article_url', models.URLField()),
                ('image_url', models.URLField()),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
