# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171029_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
