# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20171029_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.URLField(),
        ),
    ]
