# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20171029_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='old', max_length=35),
            preserve_default=False,
        ),
    ]
