# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20171030_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sources',
            old_name='source_name',
            new_name='name',
        ),
    ]
