# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20171030_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='article',
            name='urlToImage',
            field=models.URLField(max_length=300),
        ),
    ]
