# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20171031_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='urlToImage',
            field=models.URLField(max_length=500),
        ),
    ]
