# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20171031_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(default='No description provided.', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='urlToImage',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
